name: Validate with HACS

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
